services:
  serverless-api:
    image: serverless-api
    build:
      context: .
    env_file:
      - env/.env.docker
    environment:
      NODE_ENV: "docker"
    ports:
      - '8082:4000'
    command: bash -c "npm run db:migrate && NODE_ENV=docker npm run db:seed && npm run start:prod"
    networks:
      - serverless-api-network
#    volumes:
#      - learna-db:/usr/src/app
    depends_on:
      serverless-api-db:
        condition: service_healthy
  #      mailhog:
  #        condition: service_healthy
  serverless-api-db:
    image: postgres:latest
    ports:
      - '5434:5432'
    volumes:
      - serverless-api-db:/var/lib/postgresql/data
    env_file:
      - env/.env.docker
    networks:
      - serverless-api-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "learna-db" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 20s

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - serverless-api-network

networks:
  serverless-api-network:
    driver: bridge
volumes:
  serverless-api-db:
    driver: local
